// Auto-generated by BulletJS
import Home from '../views/Home';
import Errors_404 from '../views/Errors/404';
import Errors_500 from '../views/Errors/500';
import Auth_Login from '../views/Auth/Login';
import Auth_Register from '../views/Auth/Register';

export const PAGES: Record<string, any> = {
    'Home': Home,
    'Errors/404': Errors_404,
    'Errors/500': Errors_500,
    'Auth/Login': Auth_Login,
    'Auth/Register': Auth_Register
};
