
import { readdir } from 'node:fs/promises';
import { join, relative, basename, extname } from 'node:path';

export async function generatePagesManifest(viewsDir: string, outputDir: string) {
  try {
    const files = await readdir(viewsDir, { recursive: true });
    const tsxFiles = files.filter(f => f.endsWith('.tsx') && !f.includes('Layout')); // Simple filter for now

    const imports: string[] = [];
    const exports: string[] = [];

    tsxFiles.forEach((file) => {
       // handling nested paths e.g. Auth/Login.tsx -> Auth/Login
       // file is relative to viewsDir e.g. "Home.tsx" or "Auth/Login.tsx"
       
       const name = file.replace(/\.tsx$/, '');
       // keys in manifest: 'Home', 'Auth/Login'
       const componentName = name.replace(/\//g, '_'); // Auth_Login
       
       // Import path relative to outputDir
       // outputDir is resources/js
       // viewsDir is resources/views
       // relative path from js to views is ../views
       
       imports.push(`import ${componentName} from '../views/${name}';`);
       exports.push(`    '${name}': ${componentName}`);
    });

    const content = `// Auto-generated by BulletJS
${imports.join('\n')}

export const PAGES: Record<string, any> = {
${exports.join(',\n')}
};
`;

    // Write to outputDir/pages.ts
    const outputFile = join(outputDir, 'pages.ts');
    await Bun.write(outputFile, content);
    console.log('Pages manifest generated successfully.');

  } catch (error) {
    console.error('Error generating pages manifest:', error);
  }
}
